name: test-man

on:
  workflow_dispatch:

  repository_dispatch:
    types: [test-man]

jobs:
  build:

    runs-on: runs-on: macos-11.0

    steps:

    # - if: github.event.client_payload
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.ref }}
    - name: Unshallow
      run: git fetch --prune --unshallow --tags
    

    #- if: github.event.client_payload.echo_string
    - name: echo string
      run: |
           echo ${{ toJSON(github.event.client_payload.ref) }}
           echo ${{ toJSON(github.event.client_payload.username) }}
           echo ${{ toJSON(github.event.client_payload.deploy_message) }}
